import type { Bank, CardCategory, CreditCard, HomeContent } from "@/lib/types";

export const categoryLabels: Record<CardCategory, string> = {
  cashback: "Cashback",
  viajes: "Viajes",
  negocios: "Negocios",
  premium: "Premium",
  clásica: "Clásica",
  estudiante: "Estudiante",
  retail: "Retail",
  familia: "Familia",
};

export const defaultHomeContent: HomeContent = {
  sections: [
    {
      id: "section-1",
      eyebrow: "Guías rápidas",
      title: "Empieza comparando según tu estilo de gasto",
      description:
        "Si gastas más en supermercado, viajes o negocio, puedes ir directo al catálogo filtrado y evitar ruido innecesario.",
      ctaLabel: "Ir al catálogo",
      ctaHref: "/tarjetas",
    },
    {
      id: "section-2",
      eyebrow: "Ayuda personalizada",
      title: "No sabes cuál elegir? Usa el asesor inteligente",
      description:
        "Haz una pregunta natural y recibe una recomendación clara usando solo tarjetas reales disponibles en TuCredito.",
      ctaLabel: "Abrir IA",
      ctaHref: "/ia",
    },
  ],
};

export const banks: Bank[] = [
  {
    id: "popular",
    name: "Banco Popular Dominicano",
    slug: "banco-popular-dominicano",
    logoUrl: "/assets/placeholder.svg",
    description: "Institución líder con opciones clásicas y premium para distintos perfiles de consumo.",
    featured: true,
  },
  {
    id: "bhd",
    name: "BHD León",
    slug: "bhd-leon",
    logoUrl: "/assets/placeholder.svg",
    description: "Portafolio sólido con foco en cashback y beneficios cotidianos.",
    featured: true,
  },
  {
    id: "banreservas",
    name: "Banreservas",
    slug: "banreservas",
    logoUrl: "/assets/placeholder.svg",
    description: "Oferta local con productos accesibles para familias y viajeros frecuentes.",
    featured: false,
  },
  {
    id: "scotia",
    name: "Scotiabank",
    slug: "scotiabank",
    logoUrl: "/assets/placeholder.svg",
    description: "Tarjetas con enfoque internacional y empresarial.",
    featured: false,
  },
];

const now = "2025-01-15T00:00:00.000Z";

export const creditCards: CreditCard[] = [
  {
    id: "visa-clasica-popular",
    bankId: "popular",
    name: "Visa Clásica Popular",
    slug: "visa-clasica-popular",
    category: "clásica",
    imageUrl: "/assets/placeholder.svg",
    description: "<p>Tarjeta ideal para el uso diario con beneficios esenciales y costos fáciles de entender. Está pensada para quienes buscan una primera tarjeta funcional y confiable dentro del mercado dominicano.</p>",
    benefits: [
      "Sin anualidad el primer año",
      "Acceso a cuotas sin interés",
      "Promociones frecuentes en comercios locales",
    ],
    requirements: [
      "Cédula vigente",
      "Comprobante de ingresos",
      "Evaluación crediticia estándar",
    ],
    details: {
      annualFee: "RD$2,950",
      minIncome: "RD$25,000",
      currency: "DOP",
      approvalLevel: "bajo",
      highlight: "Tarjeta ideal para el uso diario con beneficios esenciales.",
      idealProfile: "Usuarios que buscan una tarjeta simple, accesible y útil para compras del día a día.",
      seoDescription: "Visa Clásica Popular en República Dominicana: beneficios esenciales, anualidad accesible y uso cotidiano.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "visa-signature-popular",
    bankId: "popular",
    name: "Visa Signature Popular",
    slug: "visa-signature-popular",
    category: "premium",
    imageUrl: "/assets/placeholder.svg",
    description: "<p>La tarjeta premium de Banco Popular con beneficios exclusivos para clientes que valoran comodidad, acceso y servicios diferenciados. Combina experiencia de viaje, protección y atención preferencial.</p>",
    benefits: [
      "Acceso a salas VIP",
      "Cashback 2%",
      "Servicio concierge y seguros en viaje",
    ],
    requirements: [
      "Cédula o pasaporte vigente",
      "Ingresos demostrables altos",
      "Perfil crediticio sólido",
    ],
    details: {
      annualFee: "RD$13,900",
      minIncome: "RD$120,000",
      currency: "USD",
      approvalLevel: "alto",
      highlight: "La tarjeta premium de Banco Popular con beneficios exclusivos.",
      idealProfile: "Clientes premium que quieren viajes, acceso preferente y recompensas elevadas.",
      seoDescription: "Visa Signature Popular: tarjeta premium en RD con beneficios exclusivos, cashback y acceso VIP.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bhd-cashback",
    bankId: "bhd",
    name: "BHD Cashback Card",
    slug: "bhd-cashback",
    category: "cashback",
    imageUrl: "/assets/placeholder.svg",
    description: "<p>Gana cashback en todas tus compras con BHD León. Es una alternativa directa para quienes quieren retorno constante en gastos recurrentes y categorías de uso masivo.</p>",
    benefits: [
      "3% cashback en supermercados",
      "1% en todo lo demás",
      "Descuentos y promociones locales",
    ],
    requirements: [
      "Documento de identidad vigente",
      "Prueba de ingresos",
      "Evaluación crediticia media",
    ],
    details: {
      annualFee: "RD$6,700",
      minIncome: "RD$55,000",
      currency: "DOP",
      approvalLevel: "medio",
      highlight: "Gana cashback en todas tus compras con BHD León.",
      idealProfile: "Usuarios que concentran gasto en supermercado, consumo local y compras regulares.",
      seoDescription: "BHD Cashback Card: tarjeta cashback en RD con devolución en supermercados y compras diarias.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "travel-banreservas",
    bankId: "banreservas",
    name: "Travel Banreservas",
    slug: "travel-banreservas",
    category: "viajes",
    imageUrl: "/assets/placeholder.svg",
    description: "<p>Tarjeta de viaje pensada para usuarios que buscan beneficios internacionales y acumulación asociada a consumo fuera del país.</p>",
    benefits: [
      "Acumulación para viajes",
      "Promociones en hoteles",
      "Coberturas internacionales básicas",
    ],
    requirements: [
      "Identificación vigente",
      "Comprobante de ingresos",
      "Evaluación crediticia del banco",
    ],
    details: {
      annualFee: "RD$7,500",
      minIncome: "RD$70,000",
      currency: "USD",
      approvalLevel: "medio",
      highlight: "Buena opción para viajeros que quieren una entrada funcional al segmento internacional.",
      idealProfile: "Personas que viajan algunas veces al año y priorizan beneficios de viaje sin ir al segmento más alto.",
      seoDescription: "Travel Banreservas: tarjeta para viajeros en República Dominicana con beneficios internacionales.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "scotia-business-one",
    bankId: "scotia",
    name: "Scotia Business One",
    slug: "scotia-business-one",
    category: "negocios",
    imageUrl: "/assets/placeholder.svg",
    description: "<p>Solución corporativa para emprendedores y profesionales que desean separar gastos personales y operativos.</p>",
    benefits: [
      "Control de gastos del negocio",
      "Tarjetas adicionales para equipo",
      "Promociones en servicios empresariales",
    ],
    requirements: [
      "Documentación comercial",
      "Ingresos o facturación comprobable",
      "Perfil financiero evaluado por el banco",
    ],
    details: {
      annualFee: "RD$9,800",
      minIncome: "RD$90,000",
      currency: "USD",
      approvalLevel: "alto",
      highlight: "Pensada para negocio y operación profesional con mejor trazabilidad de consumo.",
      idealProfile: "Emprendedores y consultores que quieren una línea separada para su operación.",
      seoDescription: "Scotia Business One: tarjeta de negocios en RD para gastos empresariales y control operativo.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
];
