import type { Bank, CardCategory, CreditCard } from "@/lib/types";

export const categoryLabels: Record<CardCategory, string> = {
  cashback: "Cashback",
  viajes: "Viajes",
  negocios: "Negocios",
  premium: "Premium",
  clásica: "Clásica",
  estudiante: "Estudiante",
  retail: "Retail",
  familia: "Familia",
};

export const banks: Bank[] = [
  {
    id: "bhd",
    name: "BHD",
    slug: "bhd",
    logoUrl: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=800&q=80",
    description: "Portafolio premium con opciones para consumo diario, viajes y clientes de alto perfil.",
    featured: true,
  },
  {
    id: "popular",
    name: "Popular",
    slug: "popular",
    logoUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    description: "Soluciones reconocidas en República Dominicana para profesionales y familias.",
    featured: true,
  },
  {
    id: "reservas",
    name: "Banreservas",
    slug: "banreservas",
    logoUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80",
    description: "Amplio alcance local, beneficios utilitarios y propuestas para consumo inteligente.",
    featured: false,
  },
  {
    id: "scotia",
    name: "Scotiabank",
    slug: "scotiabank",
    logoUrl: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=800&q=80",
    description: "Tarjetas internacionales con énfasis en premium y viajeros frecuentes.",
    featured: false,
  },
];

const now = "2025-01-15T00:00:00.000Z";

export const creditCards: CreditCard[] = [
  {
    id: "bhd-infinite",
    bankId: "bhd",
    name: "BHD Infinite Rewards",
    slug: "bhd-infinite-rewards",
    category: "premium",
    imageUrl: "https://images.unsplash.com/photo-1556742393-d75f468bfcb0?auto=format&fit=crop&w=900&q=80",
    description: "Una tarjeta diseñada para quienes quieren viajar, acumular beneficios de alto nivel y mantener una experiencia premium en cada compra. Combina acceso a salas VIP, acumulación acelerada y seguros internacionales.",
    benefits: [
      "Acceso a salas VIP en aeropuertos seleccionados",
      "Acumulación acelerada en viajes, hoteles y restaurantes",
      "Seguro de viaje y protección de compras",
      "Atención preferencial y concierge",
    ],
    requirements: [
      "Cédula o pasaporte vigente",
      "Ingresos demostrables",
      "Buen historial crediticio",
    ],
    details: {
      annualFee: "RD$16,500",
      minIncome: "RD$180,000",
      currency: "USD",
      approvalLevel: "alto",
      highlight: "Ideal para ejecutivos que viajan varias veces al año.",
      idealProfile: "Profesionales con consumo alto y enfoque en beneficios de viaje y lifestyle.",
      seoDescription: "Conoce la BHD Infinite Rewards: tarjeta premium en RD con beneficios de viaje, salas VIP y protección internacional.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
    contentBlocks: [
      { title: "Por qué destaca", body: "Ofrece un balance sólido entre beneficios tangibles y experiencia premium para viajes frecuentes." },
      { title: "Qué debes considerar", body: "Su anualidad es alta, por lo que conviene cuando aprovechas los beneficios internacionales." },
    ],
  },
  {
    id: "popular-black",
    bankId: "popular",
    name: "Popular Black Cashback",
    slug: "popular-black-cashback",
    category: "cashback",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    description: "Pensada para maximizar retorno en gastos recurrentes del día a día con una capa premium de atención y flexibilidad.",
    benefits: [
      "Cashback en supermercados y estaciones de combustible",
      "Promociones en comercios aliados en RD",
      "App robusta para seguimiento de consumos",
      "Cuotas flexibles y programa de recompensas",
    ],
    requirements: [
      "Documento de identidad vigente",
      "Carta laboral o evidencia de ingresos",
      "Historial crediticio medio o alto",
    ],
    details: {
      annualFee: "RD$9,200",
      minIncome: "RD$95,000",
      currency: "DOP",
      approvalLevel: "medio",
      highlight: "Excelente para quien gasta fuerte en consumo diario y quiere retorno inmediato.",
      idealProfile: "Profesionales jóvenes con gasto recurrente en compras locales, delivery y combustible.",
      seoDescription: "Descubre la Popular Black Cashback y compara su devolución, anualidad y perfil ideal en TuCredito.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
    contentBlocks: [
      { title: "Fortaleza principal", body: "Convierte gastos cotidianos en retorno efectivo sin sacrificar posicionamiento premium." },
    ],
  },
  {
    id: "reservas-viajes",
    bankId: "reservas",
    name: "Banreservas Travel Plus",
    slug: "banreservas-travel-plus",
    category: "viajes",
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=80",
    description: "Una opción balanceada para viajeros frecuentes dentro y fuera del Caribe, con seguros y acumulación en reservas.",
    benefits: [
      "Millas por compras internacionales",
      "Asistencia en viaje",
      "Promociones con aerolíneas y hoteles",
      "Cobertura ante demoras y equipaje",
    ],
    requirements: [
      "Identificación vigente",
      "Prueba de ingresos",
      "Referencias financieras según evaluación",
    ],
    details: {
      annualFee: "RD$7,800",
      minIncome: "RD$70,000",
      currency: "USD",
      approvalLevel: "medio",
      highlight: "Buena puerta de entrada al segmento de viajes con costo moderado.",
      idealProfile: "Usuarios que hacen 2 a 4 viajes al año y valoran protección internacional.",
      seoDescription: "Evalúa Banreservas Travel Plus: beneficios para viajes, anualidad y requisitos en República Dominicana.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "scotia-elite-business",
    bankId: "scotia",
    name: "Scotia Elite Business",
    slug: "scotia-elite-business",
    category: "negocios",
    imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
    description: "Solución enfocada en emprendedores y equipos pequeños que necesitan control de gastos, flexibilidad y presencia internacional.",
    benefits: [
      "Herramientas para separar gastos de negocio",
      "Beneficios en plataformas SaaS y viajes corporativos",
      "Tarjetas adicionales para equipo",
      "Alertas avanzadas de consumo",
    ],
    requirements: [
      "Documentación personal y comercial",
      "Prueba de ingresos o facturación",
      "Evaluación crediticia integral",
    ],
    details: {
      annualFee: "RD$11,900",
      minIncome: "RD$130,000",
      currency: "USD",
      approvalLevel: "alto",
      highlight: "Pensada para emprendedores que necesitan una tarjeta corporativa ágil y premium.",
      idealProfile: "Fundadores, ejecutivos y consultores con gasto empresarial frecuente.",
      seoDescription: "Compara Scotia Elite Business: tarjeta de negocios premium con beneficios para equipos y viajes corporativos.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "popular-clasica",
    bankId: "popular",
    name: "Popular Clásica Flex",
    slug: "popular-clasica-flex",
    category: "clásica",
    imageUrl: "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?auto=format&fit=crop&w=900&q=80",
    description: "Una alternativa para comenzar historial con beneficios claros, aprobación accesible y costos razonables.",
    benefits: [
      "Promociones mensuales en comercios locales",
      "Cuotas y diferidos",
      "App simple para seguimiento y pagos",
    ],
    requirements: [
      "Documento de identidad",
      "Comprobante de ingresos",
      "Historial básico o referencias",
    ],
    details: {
      annualFee: "RD$3,600",
      minIncome: "RD$30,000",
      currency: "DOP",
      approvalLevel: "bajo",
      highlight: "Una tarjeta de entrada bien posicionada para construir historial.",
      idealProfile: "Primeros usuarios de crédito o personas que quieren una opción simple y flexible.",
      seoDescription: "Popular Clásica Flex: tarjeta clásica en RD con anualidad accesible y requisitos más ligeros.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "bhd-student",
    bankId: "bhd",
    name: "BHD Student Start",
    slug: "bhd-student-start",
    category: "estudiante",
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80",
    description: "Tarjeta pensada para estudiantes universitarios con control, educación financiera y costos bajos.",
    benefits: [
      "Límites moderados para mejor control",
      "Promociones en educación y tecnología",
      "Alertas en tiempo real",
    ],
    requirements: [
      "Ser mayor de edad",
      "Documento de identidad",
      "Prueba de ingresos o codeudor si aplica",
    ],
    details: {
      annualFee: "RD$1,900",
      minIncome: "RD$18,000",
      currency: "DOP",
      approvalLevel: "bajo",
      highlight: "Diseñada para empezar con disciplina y acompañamiento financiero.",
      idealProfile: "Estudiantes o recién graduados que quieren crear historial crediticio.",
      seoDescription: "BHD Student Start: tarjeta para estudiantes en República Dominicana con enfoque en control y costo bajo.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "reservas-family",
    bankId: "reservas",
    name: "Banreservas Familia Plus",
    slug: "banreservas-familia-plus",
    category: "familia",
    imageUrl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=900&q=80",
    description: "Optimizada para hogares que priorizan compras en supermercado, salud y educación con beneficios locales.",
    benefits: [
      "Descuentos en supermercados y farmacias",
      "Tarjetas adicionales para núcleo familiar",
      "Financiamiento de compras seleccionadas",
    ],
    requirements: [
      "Identificación vigente",
      "Ingresos demostrables",
      "Evaluación del perfil financiero",
    ],
    details: {
      annualFee: "RD$4,900",
      minIncome: "RD$45,000",
      currency: "DOP",
      approvalLevel: "medio",
      highlight: "Excelente para centralizar gastos del hogar y aprovechar descuentos útiles.",
      idealProfile: "Familias jóvenes con alto gasto mensual en necesidades recurrentes.",
      seoDescription: "Banreservas Familia Plus: tarjeta familiar para compras del hogar, salud y educación en RD.",
    },
    featured: true,
    active: true,
    visibility: "featured",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "scotia-retail",
    bankId: "scotia",
    name: "Scotia Retail Smart",
    slug: "scotia-retail-smart",
    category: "retail",
    imageUrl: "https://images.unsplash.com/photo-1481437156560-3205f6a55735?auto=format&fit=crop&w=900&q=80",
    description: "Pensada para consumidores orientados a compras estratégicas con promociones en moda, tecnología y comercios aliados.",
    benefits: [
      "Descuentos en tiendas afiliadas",
      "Acumulación por compras online",
      "Ofertas flash durante campañas comerciales",
    ],
    requirements: [
      "Documento vigente",
      "Soporte de ingresos",
      "Evaluación crediticia estándar",
    ],
    details: {
      annualFee: "RD$4,300",
      minIncome: "RD$40,000",
      currency: "DOP",
      approvalLevel: "medio",
      highlight: "Muy útil si concentras tu consumo en retail y comercio digital.",
      idealProfile: "Compradores frecuentes que quieren valor en moda, gadgets y campañas promocionales.",
      seoDescription: "Scotia Retail Smart: tarjeta retail con beneficios en compras online y comercios aliados en RD.",
    },
    featured: false,
    active: true,
    visibility: "active",
    createdAt: now,
    updatedAt: now,
  },
];
